<div class="section-config">
    <fieldset>
        <p>
            <strong><?php echo Mage::helper('frosit_fontawesomeness')->__('Included Fonts:') ?></strong>
            <a href="http://fontawesome.io/">Font Awesome</a> -
            <a href="http://google.github.io/material-design-icons/">Google Material Icons</a> -
            <a href="http://zurb.com/playground/foundation-icon-fonts-3">Foundation Icons</a> -
            <a href="http://ionicons.com/">Ion Icons</a> -
            <a href="https://octicons.github.com/">OctIcons</a> -
            <a href="https://themify.me/themify-icons">Themify Icons</a>
        </p>
    </fieldset>
</div>