<div class="section-config">
    <fieldset>
        <table class="form-list">

            <tbody>
            <tr>
                <td class="label">
                    <h3>FROSIT</h3>
                </td>
                <td>
                    <p>
                        <a href="http://www.frosit.nl">FROSIT.nl</a>
                    </p>
                </td>
            </tr>
            </tbody>
        </table>
    </fieldset>
</div>