language: php
sudo: false

branches:
  only:
    - travis
    - master
    - staging

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  global:
  - SKIP_CLEANUP=1
  matrix:
  - MAGENTO_VERSION=magento-mirror-1.4.2.0
  - MAGENTO_VERSION=magento-mirror-1.5.1.0
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.9.2.1
  - MAGENTO_VERSION=magento-mirror-1.9.2.4
  - MAGENTO_VERSION=magento-mirror-1.9.3.0
  - MAGENTO_VERSION=magento-mirror-1.9.3.1

matrix:
  fast-finish: true
  allow_failures:
  - php: hhvm
  - php: 5.6
  exclude:
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.4.2.0"
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.5.1.0"
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.6.2.0"
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.7.0.2"
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.8.1.0"
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.4.2.0"
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.5.1.0"
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.6.2.0"
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.7.0.2"
    - php: 5.6
      env: MAGENTO_VERSION="magento-mirror-1.8.1.0"
    - php: 5.6
  include:
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.2.1"
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.2.4"
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.3.0"
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.3.1"
    - php: 7.0
      env: LINTSH=1
      script: find {src,tests} -name "*.php" ! -path '*/String.php' -print0 | xargs -0 -n1 -P8 php -l | grep -v '^No syntax errors detected'; test $? -eq 1

script:
  - curl -sSL https://raw.githubusercontent.com/frosit/MageTestStand/master/setup.sh | bash