language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
  - php: hhvm
env:
#  global:
#    - MAGENTO_DB_ALLOWSAME=1
#    - SKIP_CLEANUP=1
  - MAGENTO_VERSION=magento-mirror-1.5.1.0
  - MAGENTO_VERSION=magento-mirror-1.5.1.0
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.9.2.1
  - MAGENTO_VERSION=magento-mirror-1.9.2.4
  - MAGENTO_VERSION=magento-mirror-1.9.3.0
  - MAGENTO_VERSION=magento-mirror-1.9.3.1
script:
  - curl -sSL https://raw.githubusercontent.com/frosit/MageTestStand/master/setup.sh | bash